{% set name = "acinetoscope" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - acinetoscope = acinetoscope.acinetoscope:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    # Core Python packages from setup.py
    - pandas>=1.5.0
    - biopython>=1.85
    - psutil>=5.9.0
    - requests>=2.28.0
    - tqdm>=4.64.0
    - click>=8.0.0
    - kaptive>=3.1.0
    # HTML parsing
    - beautifulsoup4>=4.11.0
    - lxml>=4.9.0
    # Visualization 
    - matplotlib>=3.5.0
    - seaborn>=0.12.0
    - scipy>=1.10.1
    # Optional/extra (for full features)
    - plotly>=5.10.0
    # Bioinformatic tools
    - abricate >=1.2.0
    - perl
    - any2fasta
    - blast >=2.13.0
    # Perl modules
    - perl-moo
    - perl-list-moreutils
    - perl-json
    - perl-lwp-protocol-https
    - perl-path-tiny
    - perl-data-dumper
    - perl-getopt-long
    - perl-file-which
    
  commands:
    - acinetoscope --help
    
about:
  home: https://github.com/bbeckley-hub/acinetoscope
  license: MIT
  license_file: LICENSE
  summary: 'AcinetoScope: Comprehensive A. baumannii genomic typing pipeline with parallel execution'
  description: |
    AcinetoScope is a complete, automated genomic analysis pipeline for Acinetobacter baumannii, 
    featuring parallel execution for rapid processing of bacterial genomes. The pipeline integrates 
    multiple analysis modules into a unified workflow:
    
    • Quality Control (FASTA QC) - Comprehensive sequence validation
    • Multi-Locus Sequence Typing (MLST) - Oxford & Pasteur schemes
    • K/O Locus Typing (Kaptive) - Capsule and lipooligosaccharide typing
    • Antimicrobial Resistance (AMR) - Comprehensive resistance gene detection
    • Virulence & Plasmid Profiling (ABRicate) - Multi-database screening
    • Critical Genes Flagging - Priority markers for infection control
    • Interactive HTML Reports - Gene-centric integrated analysis
    • Cross-genome pattern discovery
    
    Key Features:
    🚀 Parallel Execution - All modules run simultaneously for maximum speed
    📊 Interactive Reports - HTML summaries with visualization
    🧬 Multi-Database Integration - CARD, ResFinder, VFDB, NCBI, MEGARes, BacMet
    ⚡ Easy Deployment - Single command analysis with automatic dependency handling
    🎯 Critical Gene Tracking - Carbapenemases, ESBLs, colistin/tigecycline resistance
    
    Designed for clinical microbiology, outbreak investigation, and genomic surveillance, 
    AcinetoScope provides clinical labs and researchers with a complete solution for 
    A. baumannii genomic characterization from raw sequencing data to publication-ready reports.
  doc_url: https://github.com/bbeckley-hub/acinetoscope
  dev_url: https://github.com/bbeckley-hub/acinetoscope
  
  extra:
  recipe-maintainers:
    - bbeckley-hub
