from setuptools import setup

setup(
    name="acinetoscope",
    version="1.0.0",
    author="Brown Beckley",
    author_email="brownbeckley94@gmail.com",
    description="Advanced Acinetobacter baumannii Genomic Analysis Platform",
    long_description="Complete A. baumannii genomic analysis pipeline: MLST | K/O Locus | AMR | Plasmid | Virulence | Quality Control | Critical Genes Tracked: Carbapenemases • ESBLs • Colistin Resistance • Tigecycline Resistance • Biofilm Formation • Efflux Pumps • Environmental Co-Selection | Summary Reports",
    long_description_content_type="text/markdown",
    url="https://github.com/bbeckley-hub/acinetoscope",
    packages=['acinetoscope'],
    include_package_data=True,
    python_requires=">=3.9",
    install_requires=[
        "pandas>=1.5.0",
        "biopython>=1.85",  
        "psutil>=5.9.0",
        "requests>=2.28.0",
        "tqdm>=4.64.0",
        "click>=8.0.0",
        "kaptive>=3.1.0", 
        "beautifulsoup4>=4.11.0",
        "lxml>=4.9.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.12.0",
    ],
    entry_points={
        "console_scripts": [
            "acinetoscope=acinetoscope.acinetoscope:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
    ],
)